server.port: 80
spring.profiles: default
security.jwt:
  tokenExpirationTime: 2880 # Number of minutes / 1 week
  refreshTokenExpTime: 263520 # Minutes / 183 days
  tokenIssuer: http://bobrchess.of.by
  tokenSigningKey: aaaa
spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB